apiVersion: v1
kind: Service
metadata:
  name: flask-python-server
spec:
  selector:
    app: python-flask
  ports:
    - protocol: "TCP"
      port: 5001
      targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: python-flask
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: python-flask
    spec:
      containers:
        - name: python-flask
          image: python-flask:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
